-- 求人・雇用掲載管理サイト テーブル作成SQL
-- PostgreSQL 16+ / Spring Boot / Flyway想定
-- 文字コード: UTF-8

BEGIN;

CREATE SCHEMA IF NOT EXISTS urabus_schema;
SET search_path TO urabus_schema, public;

-- =========================================================
-- 1. 認証・ユーザー
-- =========================================================
CREATE TABLE m_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type VARCHAR(20) NOT NULL CHECK (user_type IN ('USER','COMPANY','OPERATOR')),
    email VARCHAR(254) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','WITHDRAWN')),
    email_verified_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);
CREATE UNIQUE INDEX uq_m_user_email_active ON m_user (lower(email)) WHERE deleted_at IS NULL;

CREATE TABLE t_user_authentication (
    user_id BIGINT PRIMARY KEY REFERENCES m_user(user_id) ON DELETE CASCADE,
    password_hash VARCHAR(255),
    failed_login_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
    locked_until TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_refresh_token (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES m_user(user_id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    device_name VARCHAR(200),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_refresh_token_user ON t_refresh_token(user_id, expires_at DESC);

CREATE TABLE t_user_profile (
    user_id BIGINT PRIMARY KEY REFERENCES m_user(user_id) ON DELETE CASCADE,
    display_name VARCHAR(100) NOT NULL,
    family_name VARCHAR(80) NOT NULL,
    given_name VARCHAR(80) NOT NULL,
    birth_date DATE,
    prefecture_code CHAR(2),
    city VARCHAR(100),
    profile_summary TEXT,
    profile_image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_user_privacy_setting (
    user_id BIGINT PRIMARY KEY REFERENCES m_user(user_id) ON DELETE CASCADE,
    searchable_by_company BOOLEAN NOT NULL DEFAULT TRUE,
    accepts_scout BOOLEAN NOT NULL DEFAULT TRUE,
    show_real_name BOOLEAN NOT NULL DEFAULT FALSE,
    show_work_history BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- 2. 経歴
-- =========================================================
CREATE TABLE m_skill (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(100) NOT NULL UNIQUE,
    category_name VARCHAR(100),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE t_resume (
    resume_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    resume_name VARCHAR(100) NOT NULL,
    summary TEXT,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    UNIQUE (resume_id, user_id)
);
CREATE INDEX idx_resume_user ON t_resume(user_id, updated_at DESC);

CREATE TABLE t_resume_work_history (
    work_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL REFERENCES t_resume(resume_id) ON DELETE CASCADE,
    company_name VARCHAR(200) NOT NULL,
    position_name VARCHAR(100),
    started_on DATE NOT NULL,
    ended_on DATE,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    CHECK (ended_on IS NULL OR ended_on >= started_on)
);

CREATE TABLE t_resume_education (
    education_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL REFERENCES t_resume(resume_id) ON DELETE CASCADE,
    school_name VARCHAR(200) NOT NULL,
    faculty_name VARCHAR(200),
    started_on DATE,
    ended_on DATE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('GRADUATED','EXPECTED','WITHDRAWN','ENROLLED')),
    display_order INTEGER NOT NULL DEFAULT 0,
    CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on)
);

CREATE TABLE t_resume_skill (
    resume_skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL REFERENCES t_resume(resume_id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES m_skill(skill_id),
    experience_years NUMERIC(4,1) CHECK (experience_years >= 0),
    proficiency_level SMALLINT CHECK (proficiency_level BETWEEN 1 AND 5),
    note TEXT,
    UNIQUE (resume_id, skill_id)
);

-- =========================================================
-- 3. 企業・企業権限
-- =========================================================
CREATE TABLE m_company (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    corporate_number CHAR(13),
    owner_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    description TEXT,
    website_url TEXT,
    prefecture_code CHAR(2),
    address TEXT,
    verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (verification_status IN ('PENDING','APPROVED','REJECTED')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);
CREATE UNIQUE INDEX uq_company_number ON m_company(corporate_number) WHERE corporate_number IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE t_company_membership (
    membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    membership_type VARCHAR(20) NOT NULL CHECK (membership_type IN ('OWNER','EMPLOYEE')),
    status VARCHAR(20) NOT NULL DEFAULT 'INVITED' CHECK (status IN ('INVITED','ACTIVE','SUSPENDED','LEFT')),
    joined_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_company_membership_active ON t_company_membership(company_id,user_id) WHERE deleted_at IS NULL;

CREATE TABLE m_company_permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(80) NOT NULL UNIQUE,
    permission_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_company_role (
    company_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES m_company(company_id) ON DELETE CASCADE,
    role_code VARCHAR(50) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_company_role_code ON t_company_role(company_id,role_code) WHERE deleted_at IS NULL;

CREATE TABLE t_company_role_permission (
    company_role_id BIGINT NOT NULL REFERENCES t_company_role(company_role_id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES m_company_permission(permission_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (company_role_id, permission_id)
);

CREATE TABLE t_company_member_role (
    membership_id BIGINT NOT NULL REFERENCES t_company_membership(membership_id) ON DELETE CASCADE,
    company_role_id BIGINT NOT NULL REFERENCES t_company_role(company_role_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (membership_id, company_role_id)
);

-- =========================================================
-- 4. 求人
-- =========================================================
CREATE TABLE m_job_feature (
    feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_name VARCHAR(100) NOT NULL UNIQUE,
    feature_group_name VARCHAR(100),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE t_job_posting (
    job_posting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    created_by_membership_id BIGINT NOT NULL REFERENCES t_company_membership(membership_id),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    employment_type_code VARCHAR(30) NOT NULL,
    salary_min NUMERIC(12,0),
    salary_max NUMERIC(12,0),
    salary_period VARCHAR(20) CHECK (salary_period IN ('HOURLY','DAILY','MONTHLY','YEARLY')),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PENDING_REVIEW','PUBLISHED','REJECTED','PAUSED','CLOSED')),
    published_at TIMESTAMPTZ,
    application_deadline TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CHECK (salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min)
);
CREATE INDEX idx_job_public ON t_job_posting(status,published_at DESC);
CREATE INDEX idx_job_company ON t_job_posting(company_id,status,updated_at DESC);

CREATE TABLE t_job_requirement (
    job_posting_id BIGINT PRIMARY KEY REFERENCES t_job_posting(job_posting_id) ON DELETE CASCADE,
    required_experience TEXT,
    required_education TEXT,
    required_qualification TEXT,
    preferred_condition TEXT,
    minimum_age SMALLINT,
    maximum_age SMALLINT,
    CHECK (maximum_age IS NULL OR minimum_age IS NULL OR maximum_age >= minimum_age)
);

CREATE TABLE t_job_work_location (
    job_work_location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL REFERENCES t_job_posting(job_posting_id) ON DELETE CASCADE,
    prefecture_code CHAR(2),
    city VARCHAR(100),
    address TEXT,
    remote_type VARCHAR(20) NOT NULL DEFAULT 'ONSITE' CHECK (remote_type IN ('ONSITE','HYBRID','FULL_REMOTE')),
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE t_job_feature (
    job_posting_id BIGINT NOT NULL REFERENCES t_job_posting(job_posting_id) ON DELETE CASCADE,
    feature_id BIGINT NOT NULL REFERENCES m_job_feature(feature_id),
    PRIMARY KEY (job_posting_id, feature_id)
);

CREATE TABLE t_job_favorite (
    user_id BIGINT NOT NULL REFERENCES m_user(user_id) ON DELETE CASCADE,
    job_posting_id BIGINT NOT NULL REFERENCES t_job_posting(job_posting_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, job_posting_id)
);

CREATE TABLE t_job_comparison (
    user_id BIGINT NOT NULL REFERENCES m_user(user_id) ON DELETE CASCADE,
    job_posting_id BIGINT NOT NULL REFERENCES t_job_posting(job_posting_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, job_posting_id)
);

-- =========================================================
-- 5. 応募・採用・スカウト
-- =========================================================
CREATE TABLE t_job_application (
    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL REFERENCES t_job_posting(job_posting_id),
    applicant_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    resume_id BIGINT NOT NULL REFERENCES t_resume(resume_id),
    motivation TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'APPLIED' CHECK (status IN ('APPLIED','SCREENING','INTERVIEW','OFFERED','HIRED','REJECTED','WITHDRAWN','DECLINED')),
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_by_membership_id BIGINT REFERENCES t_company_membership(membership_id),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_job_application_active ON t_job_application(job_posting_id,applicant_user_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_application_user ON t_job_application(applicant_user_id,applied_at DESC);
CREATE INDEX idx_application_job ON t_job_application(job_posting_id,status,applied_at DESC);

CREATE TABLE t_application_status_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES t_job_application(application_id) ON DELETE CASCADE,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    changed_by_user_id BIGINT REFERENCES m_user(user_id),
    reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_employment (
    employment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE REFERENCES t_job_application(application_id),
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('OFFERED','EMPLOYED','ENDED')),
    started_on DATE,
    ended_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on)
);
CREATE INDEX idx_employment_company ON t_employment(company_id,status,user_id);

CREATE TABLE t_scout (
    scout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    target_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    job_posting_id BIGINT REFERENCES t_job_posting(job_posting_id),
    sent_by_membership_id BIGINT NOT NULL REFERENCES t_company_membership(membership_id),
    subject VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','SENT','ACCEPTED','DECLINED','EXPIRED')),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_scout_target ON t_scout(target_user_id,status,created_at DESC);

CREATE TABLE t_scout_status_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scout_id BIGINT NOT NULL REFERENCES t_scout(scout_id) ON DELETE CASCADE,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    changed_by_user_id BIGINT REFERENCES m_user(user_id),
    reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- 6. チャット
-- =========================================================
CREATE TABLE t_chat_room (
    chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type VARCHAR(30) NOT NULL CHECK (room_type IN ('APPLICATION','SCOUT','COMPANY_CONTACT')),
    application_id BIGINT UNIQUE REFERENCES t_job_application(application_id),
    scout_id BIGINT UNIQUE REFERENCES t_scout(scout_id),
    employment_id BIGINT UNIQUE REFERENCES t_employment(employment_id),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED','ARCHIVED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
      (room_type='APPLICATION' AND application_id IS NOT NULL AND scout_id IS NULL AND employment_id IS NULL) OR
      (room_type='SCOUT' AND scout_id IS NOT NULL AND application_id IS NULL AND employment_id IS NULL) OR
      (room_type='COMPANY_CONTACT' AND employment_id IS NOT NULL AND application_id IS NULL AND scout_id IS NULL)
    )
);

CREATE TABLE t_chat_participant (
    chat_room_id BIGINT NOT NULL REFERENCES t_chat_room(chat_room_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    last_read_message_id BIGINT,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (chat_room_id,user_id)
);
CREATE INDEX idx_chat_participant_user ON t_chat_participant(user_id,chat_room_id);

CREATE TABLE t_chat_message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL REFERENCES t_chat_room(chat_room_id) ON DELETE CASCADE,
    sender_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT' CHECK (message_type IN ('TEXT','FILE','SYSTEM')),
    body TEXT,
    reply_to_message_id BIGINT REFERENCES t_chat_message(message_id),
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CHECK (message_type <> 'TEXT' OR body IS NOT NULL)
);
CREATE INDEX idx_chat_message_cursor ON t_chat_message(chat_room_id,message_id DESC);
ALTER TABLE t_chat_participant ADD CONSTRAINT fk_participant_last_read FOREIGN KEY(last_read_message_id) REFERENCES t_chat_message(message_id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE t_chat_attachment (
    attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES t_chat_message(message_id) ON DELETE CASCADE,
    storage_key TEXT NOT NULL UNIQUE,
    original_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- 7. 評価
-- =========================================================
CREATE TABLE t_company_review (
    company_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    reviewer_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    employment_id BIGINT REFERENCES t_employment(employment_id),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title VARCHAR(150),
    comment TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE' CHECK (status IN ('VISIBLE','HIDDEN','REVIEWING')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_company_review_relation ON t_company_review(employment_id,reviewer_user_id) WHERE employment_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE t_user_review (
    user_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    reviewer_membership_id BIGINT NOT NULL REFERENCES t_company_membership(membership_id),
    employment_id BIGINT REFERENCES t_employment(employment_id),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE' CHECK (status IN ('VISIBLE','HIDDEN','REVIEWING')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_user_review_relation ON t_user_review(employment_id,company_id) WHERE employment_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE t_review_report (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    review_type VARCHAR(20) NOT NULL CHECK (review_type IN ('COMPANY','USER')),
    company_review_id BIGINT REFERENCES t_company_review(company_review_id),
    user_review_id BIGINT REFERENCES t_user_review(user_review_id),
    reason_code VARCHAR(30) NOT NULL,
    detail TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','INVESTIGATING','RESOLVED','REJECTED')),
    handled_by_user_id BIGINT REFERENCES m_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((review_type='COMPANY' AND company_review_id IS NOT NULL AND user_review_id IS NULL) OR (review_type='USER' AND user_review_id IS NOT NULL AND company_review_id IS NULL))
);

-- =========================================================
-- 8. 運営・監視・収益・共通
-- =========================================================
CREATE TABLE m_operator_role (
    operator_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_operator_user_role (
    user_id BIGINT NOT NULL REFERENCES m_user(user_id) ON DELETE CASCADE,
    operator_role_id BIGINT NOT NULL REFERENCES m_operator_role(operator_role_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id,operator_role_id)
);

CREATE TABLE t_monitor_metric (
    metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_type VARCHAR(40) NOT NULL,
    bucket_start TIMESTAMPTZ NOT NULL,
    bucket_minutes INTEGER NOT NULL CHECK (bucket_minutes > 0),
    metric_value NUMERIC(18,4) NOT NULL,
    dimension_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(metric_type,bucket_start,bucket_minutes)
);

CREATE TABLE t_error_event (
    error_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('INFO','WARNING','CRITICAL')),
    service_name VARCHAR(100) NOT NULL,
    error_code VARCHAR(100),
    summary TEXT NOT NULL,
    correlation_id UUID,
    source_log_url TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_error_event_time ON t_error_event(occurred_at DESC,severity);

CREATE TABLE t_alarm_rule (
    alarm_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(150) NOT NULL,
    metric_type VARCHAR(40) NOT NULL,
    comparison_operator VARCHAR(10) NOT NULL CHECK (comparison_operator IN ('GT','GTE','LT','LTE')),
    threshold_value NUMERIC(18,4) NOT NULL,
    window_minutes INTEGER NOT NULL CHECK (window_minutes > 0),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('INFO','WARNING','CRITICAL')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id BIGINT NOT NULL REFERENCES m_user(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_alarm_notification_target (
    target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_rule_id BIGINT NOT NULL REFERENCES t_alarm_rule(alarm_rule_id) ON DELETE CASCADE,
    target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('EMAIL','WEBHOOK','SLACK')),
    target_value TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE t_alarm_history (
    alarm_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_rule_id BIGINT NOT NULL REFERENCES t_alarm_rule(alarm_rule_id),
    error_event_id BIGINT REFERENCES t_error_event(error_event_id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN','ACKNOWLEDGED','RESOLVED')),
    measured_value NUMERIC(18,4),
    fired_at TIMESTAMPTZ NOT NULL,
    acknowledged_by_user_id BIGINT REFERENCES m_user(user_id),
    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    note TEXT
);

CREATE TABLE t_billing_transaction (
    billing_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES m_company(company_id),
    provider VARCHAR(30) NOT NULL,
    provider_transaction_id VARCHAR(150) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('CHARGE','REFUND','ADJUSTMENT')),
    amount NUMERIC(12,0) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'JPY',
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','SUCCEEDED','FAILED','REFUNDED')),
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider,provider_transaction_id)
);

CREATE TABLE t_audit_log (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES m_user(user_id),
    action_code VARCHAR(80) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    before_data JSONB,
    after_data JSONB,
    ip_address INET,
    user_agent TEXT,
    correlation_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_target ON t_audit_log(target_type,target_id,created_at DESC);

CREATE TABLE t_outbox_event (
    outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','PUBLISHED','FAILED')),
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_outbox_dispatch ON t_outbox_event(status,available_at);

COMMENT ON SCHEMA urabus_schema IS '求人・雇用掲載管理サイト';
COMMENT ON TABLE m_user IS '登録ユーザー。未登録ユーザーはレコードを持たない';
COMMENT ON TABLE t_company_membership IS '企業ユーザーと企業の所属関係';
COMMENT ON TABLE t_company_role_permission IS '企業単位の可変RBAC権限';
COMMENT ON TABLE t_chat_room IS '応募・スカウト・雇用後連絡の共通チャットルーム';
COMMENT ON TABLE t_monitor_metric IS 'モニター画面向け集計メトリクス';

COMMIT;
