import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import FavoriteButton from "./FavoriteButton";
import { SEARCH_COLORS as C, SEARCH_SHADOW } from "./theme";
import type { CompanySearchItem } from "./types";

export default function CompanySearchCard({item,onPressDetail,onPressJobs}:{item:CompanySearchItem;onPressDetail:(id:number)=>void;onPressJobs:(id:number)=>void}){return <View style={s.card}><View style={s.head}><View style={[s.mark,{backgroundColor:item.markColor}]}><Text style={s.markText}>{item.mark}</Text></View><View style={{flex:1}}><View style={s.nameRow}><Text style={s.name}>{item.companyName}</Text><View style={s.verified}><Text style={s.verifiedText}>審査済み</Text></View></View><Text style={s.sub}>{item.industry}　／　{item.location}</Text></View><FavoriteButton type="heart" label={item.companyName}/></View><View style={s.scoreArea}><View style={s.total}><Text style={s.totalScore}>{item.rating.toFixed(1)}</Text><Text style={s.stars}>★★★★★</Text><Text style={s.reviewCount}>{item.reviewCount.toLocaleString()}件の評価</Text></View><View style={s.scoreList}>{item.scores.map(score=><View key={score.label} style={s.scoreRow}><Text style={s.scoreLabel}>{score.label}</Text><View style={s.bar}><View style={[s.fill,{width:score.value*20}]}/></View><Text style={s.scoreNo}>{score.value.toFixed(1)}</Text></View>)}</View></View><Text style={s.description}>{item.description}</Text><View style={s.stats}><Stat value={`${item.openJobCount}件`} label="公開求人" icon="folder-open-outline"/><Stat value={`${item.reviewParticipationRate}%`} label="評価協力率" icon="sync-outline"/><Stat value={item.employeeRange} label="従業員数" icon="people-outline"/></View><View style={s.actions}><Button label="企業詳細を見る" outline onPress={()=>onPressDetail(item.id)}/><Button label={`求人を見る（${item.openJobCount}件）`} onPress={()=>onPressJobs(item.id)}/></View></View>}
function Stat({value,label,icon}:{value:string;label:string;icon:keyof typeof Ionicons.glyphMap}){return <View style={s.stat}><Ionicons name={icon} size={15} color={C.textSub}/><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
function Button({label,outline=false,onPress}:{label:string;outline?:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.button,outline&&s.buttonOutline,pressed&&{opacity:.68}]}><Text style={[s.buttonText,outline&&s.buttonTextOutline]}>{label}</Text></Pressable>}
const s=StyleSheet.create({card:{width:"48.8%",minWidth:330,flexGrow:1,borderRadius:13,borderWidth:1,borderColor:C.border,backgroundColor:C.white,padding:17,gap:13,...SEARCH_SHADOW},head:{flexDirection:"row",alignItems:"center",gap:12},mark:{width:60,height:60,borderRadius:12,alignItems:"center",justifyContent:"center"},markText:{color:C.white,fontSize:22,fontWeight:"900"},nameRow:{flexDirection:"row",alignItems:"center",flexWrap:"wrap",gap:7},name:{color:C.primaryDark,fontSize:17,fontWeight:"900"},verified:{borderRadius:5,borderWidth:1,borderColor:C.success,backgroundColor:C.successSoft,paddingHorizontal:7,paddingVertical:3},verifiedText:{color:C.success,fontSize:8.5,fontWeight:"900"},sub:{marginTop:5,color:C.textSub,fontSize:10.5},scoreArea:{borderRadius:10,backgroundColor:C.background,padding:12,flexDirection:"row",alignItems:"center",gap:18},total:{width:105,alignItems:"center"},totalScore:{color:C.text,fontSize:26,fontWeight:"900"},stars:{color:C.success,fontSize:15,letterSpacing:1},reviewCount:{marginTop:3,color:C.textSub,fontSize:8.5},scoreList:{flex:1,gap:7},scoreRow:{flexDirection:"row",alignItems:"center",gap:7},scoreLabel:{width:103,color:C.textSub,fontSize:9},bar:{flex:1,height:6,borderRadius:3,backgroundColor:C.border,overflow:"hidden"},fill:{height:"100%",borderRadius:3,backgroundColor:C.success},scoreNo:{width:24,color:C.text,fontSize:9.5,fontWeight:"800",textAlign:"right"},description:{color:C.textSub,fontSize:11,lineHeight:17},stats:{borderTopWidth:1,borderBottomWidth:1,borderColor:C.border,paddingVertical:10,flexDirection:"row",justifyContent:"space-around"},stat:{alignItems:"center",gap:2},statValue:{color:C.text,fontSize:13,fontWeight:"900"},statLabel:{color:C.textSub,fontSize:8.5},actions:{flexDirection:"row",gap:9},button:{minHeight:40,flex:1,borderRadius:8,borderWidth:1,borderColor:C.primary,backgroundColor:C.primary,alignItems:"center",justifyContent:"center",paddingHorizontal:11},buttonOutline:{backgroundColor:C.white},buttonText:{color:C.white,fontSize:11.5,fontWeight:"900"},buttonTextOutline:{color:C.primary}});
