import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import FavoriteButton from "./FavoriteButton";
import { SEARCH_COLORS as C, SEARCH_SHADOW } from "./theme";
import type { JobSearchItem } from "./types";

export default function JobSearchCard({ item, onPressDetail, onPressApply }: { item: JobSearchItem; onPressDetail: (id: number) => void; onPressApply: (id: number) => void }) {
  return <View style={s.card}><View style={[s.mark,{backgroundColor:item.markColor}]}><Text style={s.markText}>{item.mark}</Text></View><View style={s.body}><View style={s.head}><View style={{flex:1}}><Text style={s.title}>{item.title}</Text><Text style={s.company}>{item.companyName}</Text></View><FavoriteButton label={item.title} /></View><View style={s.metaRow}><Ionicons name="location-outline" size={15} color={C.textSub}/><Text style={s.meta}>{item.location}</Text><Text style={s.dot}>•</Text><Text style={s.meta}>{item.workStyle}</Text><Tag label={item.employmentType}/><Text style={s.rating}>★ {item.rating.toFixed(1)}（{item.reviewCount}件）</Text></View><Text style={s.salary}>月給 {item.salary}</Text><View style={s.tags}>{item.tags.map((tag,i)=><Tag key={tag} label={tag} purple={i%2===1}/>)}</View><Text style={s.description}>{item.description}</Text><View style={s.actions}><Button label="詳細を見る" outline onPress={()=>onPressDetail(item.id)}/><Button label="応募する" onPress={()=>onPressApply(item.id)}/></View></View></View>;
}
function Tag({label,purple=false}:{label:string;purple?:boolean}){return <View style={[s.tag,purple&&s.tagPurple]}><Text style={[s.tagText,purple&&{color:C.purple}]}>{label}</Text></View>}
function Button({label,outline=false,onPress}:{label:string;outline?:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.button,outline&&s.buttonOutline,pressed&&{opacity:.68}]}><Text style={[s.buttonText,outline&&s.buttonTextOutline]}>{label}</Text></Pressable>}
const s=StyleSheet.create({card:{borderRadius:13,borderWidth:1,borderColor:C.border,backgroundColor:C.white,padding:17,flexDirection:"row",alignItems:"flex-start",gap:14,...SEARCH_SHADOW},mark:{width:58,height:58,borderRadius:11,alignItems:"center",justifyContent:"center"},markText:{color:C.white,fontSize:20,fontWeight:"900"},body:{flex:1,minWidth:0},head:{flexDirection:"row",alignItems:"flex-start",gap:10},title:{color:C.primaryDark,fontSize:17,fontWeight:"900"},company:{marginTop:4,color:C.textSub,fontSize:11.5},metaRow:{marginTop:10,flexDirection:"row",alignItems:"center",flexWrap:"wrap",gap:6},meta:{color:C.textSub,fontSize:10.5},dot:{color:C.textMuted},rating:{color:"#A86D00",fontSize:10.5,fontWeight:"800"},salary:{marginTop:10,color:C.text,fontSize:16,fontWeight:"900"},tags:{marginTop:9,flexDirection:"row",flexWrap:"wrap",gap:6},tag:{borderRadius:6,backgroundColor:C.primarySoft,paddingHorizontal:8,paddingVertical:4},tagPurple:{backgroundColor:C.purpleSoft},tagText:{color:C.primaryDark,fontSize:9.5,fontWeight:"700"},description:{marginTop:10,color:C.textSub,fontSize:11,lineHeight:17},actions:{marginTop:13,flexDirection:"row",justifyContent:"flex-end",gap:9},button:{minWidth:145,minHeight:40,borderRadius:8,borderWidth:1,borderColor:C.primary,backgroundColor:C.primary,alignItems:"center",justifyContent:"center",paddingHorizontal:15},buttonOutline:{backgroundColor:C.white},buttonText:{color:C.white,fontSize:12,fontWeight:"900"},buttonTextOutline:{color:C.primary}});
