import { Ionicons } from "@expo/vector-icons";
import type { PropsWithChildren, ReactNode } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SEARCH_COLORS as C, SEARCH_SHADOW } from "@/components/search/theme";

export function Panel({children,style}:{children:ReactNode;style?:object}){return <View style={[s.panel,style]}>{children}</View>}
export function SectionTitle({children}:{children:ReactNode}){return <Text style={s.sectionTitle}>{children}</Text>}
export function BodyText({children}:{children:ReactNode}){return <Text style={s.body}>{children}</Text>}
export function AppButton({label,outline=false,danger=false,onPress}:{label:string;outline?:boolean;danger?:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.button,outline&&s.outline,danger&&s.danger,pressed&&s.pressed]}><Text style={[s.buttonText,outline&&s.outlineText]}>{label}</Text></Pressable>}
export function StatusBadge({label,tone="blue"}:{label:string;tone?:"blue"|"green"|"yellow"|"red"}){return <View style={[s.badge,tone==="green"&&s.badgeGreen,tone==="yellow"&&s.badgeYellow,tone==="red"&&s.badgeRed]}><Text style={[s.badgeText,tone==="green"&&{color:C.success},tone==="yellow"&&{color:"#9A6800"},tone==="red"&&{color:C.danger}]}>{label}</Text></View>}
export function FormField({label,placeholder,large=false,value,onChangeText}:{label:string;placeholder:string;large?:boolean;value?:string;onChangeText?:(value:string)=>void}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={C.textMuted} multiline={large} style={[s.input,large&&s.textarea]}/></View>}
export function StatCard({label,value,change}:{label:string;value:string;change?:string}){return <Panel style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text>{change&&<Text style={s.change}>{change}</Text>}</Panel>}
export function DataTable({headers,rows}:{headers:string[];rows:string[][]}){return <ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={s.table}><View style={s.row}>{headers.map(x=><Text key={x} style={[s.cell,s.head]}>{x}</Text>)}</View>{rows.map((row,i)=><View key={i} style={s.row}>{row.map((x,n)=><Text key={`${i}-${n}`} style={[s.cell,n===0&&s.first]}>{x}</Text>)}</View>)}</View></ScrollView>}
export function EmptyIcon({name}:{name:keyof typeof Ionicons.glyphMap}){return <View style={s.icon}><Ionicons name={name} size={26} color={C.primary}/></View>}
export function TwoColumn({children}:{children:ReactNode}){return <View style={s.two}>{children}</View>}
export function KpiRow({children}:{children:ReactNode}){return <View style={s.kpis}>{children}</View>}
const s=StyleSheet.create({panel:{borderRadius:13,borderWidth:1,borderColor:C.border,backgroundColor:C.white,padding:16,gap:12,...SEARCH_SHADOW},sectionTitle:{color:C.text,fontSize:16,fontWeight:"900"},body:{color:C.textSub,fontSize:12.5,lineHeight:20},button:{minHeight:42,minWidth:110,flexGrow:1,borderRadius:8,borderWidth:1,borderColor:C.primary,backgroundColor:C.primary,paddingHorizontal:15,alignItems:"center",justifyContent:"center"},outline:{backgroundColor:C.white},danger:{backgroundColor:C.danger,borderColor:C.danger},buttonText:{color:C.white,fontSize:12,fontWeight:"900"},outlineText:{color:C.primary},pressed:{opacity:.68},badge:{alignSelf:"flex-start",borderRadius:99,backgroundColor:C.primarySoft,paddingHorizontal:9,paddingVertical:5},badgeGreen:{backgroundColor:C.successSoft},badgeYellow:{backgroundColor:"#FFF5D8"},badgeRed:{backgroundColor:"#FDECEC"},badgeText:{color:C.primaryDark,fontSize:9.5,fontWeight:"800"},field:{gap:6},label:{color:C.text,fontSize:11.5,fontWeight:"800"},input:{minHeight:43,borderRadius:8,borderWidth:1,borderColor:C.border,paddingHorizontal:12,color:C.text,fontSize:12},textarea:{minHeight:105,textAlignVertical:"top",paddingTop:12},stat:{flex:1,minWidth:160},statLabel:{color:C.textSub,fontSize:11},statValue:{color:C.text,fontSize:24,fontWeight:"900"},change:{color:C.success,fontSize:10,fontWeight:"700"},table:{minWidth:760},row:{minHeight:43,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:C.border},cell:{width:140,paddingHorizontal:9,color:C.textSub,fontSize:10.5},head:{color:C.text,fontWeight:"900",backgroundColor:"#F8FAFD",paddingVertical:12},first:{color:C.primaryDark,fontWeight:"800"},icon:{width:50,height:50,borderRadius:14,backgroundColor:C.primarySoft,alignItems:"center",justifyContent:"center"},two:{flexDirection:"row",flexWrap:"wrap",gap:14},kpis:{flexDirection:"row",flexWrap:"wrap",gap:12}});
